[package]
name = "gwent_api"
version = "0.1.0"
authors = ["Andrés Saraos Luna <eldruz@protonmail.com>"]

[dependencies]
reqwest = "0.7.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev_dependencies]
serenity = "0.3"